export enum TABLE_CONFIG {
  ITEMS_PER_PAGE_LG = 24,
  ITEMS_PER_LINE_LG = 8,
  ITEMS_PER_PAGE_SM = 12,
  ITEMS_PER_LINE_SM = 2,
  ITEMS_PER_PAGE_MD = 18,
  ITEMS_PER_LINE_MD = 6,
  ITEMS_PER_PAGE_XL = 30,
  ITEMS_PER_LINE_XL = 10,
  ITEMS_PER_PAGE_2XL = 36,
  ITEMS_PER_LINE_2XL = 12,
}
